const data = {
  products: [
    {
        name: 'Hyundai Alcazar',
        slug: 'Hyundai Alcazar',
        category: 'Shirts',
        image: 'https://images.carandbike.com/cms/large_hyundai_alcazar_petrol_automatic_review_2_8a54e4439b.webp',
        price: 16.77 ,
        countInStock: 20,
        brand: 'Adidas',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
    {
      name: 'Hyundai i20',
      slug: 'Hyundai i20',
      category: 'Shirts',
      image: 'https://imgd.aeplcdn.com/0x0/n/cw/ec/40530/i20-exterior-right-front-three-quarter-5.jpeg', // 679px × 829px
      price:7.19 ,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    
    {
      name: 'Hyundai creta ',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: 'https://bsmedia.business-standard.com/_media/bs/img/article/2020-03/04/full/1583323049-9188.png?im=FeatureCrop,width=826,height=465',
      price: 10.87,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'hyundai iconic 5',
      slug: 'hyundai iconic 5',
      category: 'Pants',
      image: 'https://cdni.autocarindia.com/Utils/ImageResizer.ashx?n=https://cdni.autocarindia.com/ExtraImages/20221221053459_Ioniq_5_factory.jpg&w=700&q=90&c=1',
      price: 5.73,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
        name: 'Grand i10 Nios',
        slug: 'Grand i10 Nios',
        category: 'Pants',
        image: 'https://stimg.cardekho.com/images/carexteriorimages/930x620/Hyundai/Grand-i10-Nios/7091/Hyundai-Grand-i10-Nios-Sportz/1583742828294/front-left-side-47.jpg',
        price: 5.73,
        countInStock: 5,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
    //   {
    //     name: 'Hyundai Alcazar',
    //     slug: 'Hyundai Alcazar',
    //     category: 'Shirts',
    //     image: 'https://images.carandbike.com/cms/large_hyundai_alcazar_petrol_automatic_review_2_8a54e4439b.webp',
    //     price: 16.77 ,
    //     countInStock: 20,
    //     brand: 'Adidas',
    //     rating: 4.0,
    //     numReviews: 10,
    //     description: 'high quality product',
    //   },
      {
          name: 'Hyundai verna',
          slug: 'Hyundai verna',
        category: 'Pants',
        image: 'https://stimg.cardekho.com/images/cms/carnewsimages/editorimages/6427184e55d90.jpg?impolicy=resize&imwidth=420',
        price: 5.73,
        countInStock: 5,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        name: 'Hyundai Tucson',
        slug: 'Hyundai Tucson',
        category: 'Pants',
        image: 'https://stimg.cardekho.com/images/carexteriorimages/930x620/Hyundai/Tucson/7995/1677916817354/front-left-side-47.jpg',
        price: 5.73,
        countInStock: 5,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
  ],
};
export default data;